
<AddAuto>
    size_hint_y: None
    height: "150dp"
    # padding:'10dp', 0
    orientation:'vertical'
    spacing:'20dp'
    MDTextField:
        id:marka
        mode:'rectangle'
        hint_text:'Marka auto'
        font_size:'28sp'
        required:True
    MDTextField:
        id:model
        mode:'rectangle'
        hint_text:'Model auto'
        font_size:'28sp'
        required:True


