<ListItem>
    divider:None
    text:root.text
    bg_color:app.theme_cls.primary_color

    radius: [25, 0, 25, 0]
    font_style:'H6'

    IconRightWidget:
        id:btn_delete
        icon:'trash-can-outline'
        theme_icon_color:'Custom'
        icon_color:'black'
    IconLeftWidget:
        id:btn_edit
        icon: "pencil"
        theme_icon_color:'Custom'
        icon_color:'black'